workspace:
  base: /data/lnmp
  path: .

pipeline:
  bash:
    image: khs1994/php:7.4.3-composer-alpine
    commands:
      - pwd
      - bash ./lnmp-docker

  # https://hub.docker.com/_/microsoft-powershell?tab=description
  powershell:
    image: mcr.azk8s.cn/powershell:preview-alpine-3.10
    commands:
      - pwsh ./lnmp-docker.ps1

branches:
- master
- 19.03
